# Generated by Django 5.0.6 on 2024-06-29 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_friendship_alter_user_friends'),
    ]

    operations = [

    ]
