# Generated by Django 5.0.6 on 2024-06-29 12:50

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("chess", "0004_alter_user_friends_delete_friendship"),
    ]

    operations = [
    ]
