# Generated by Django 5.0.6 on 2024-06-29 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0005_auto_20240629_1750'),
    ]

    operations = [
    ]
