# Generated by Django 5.0.6 on 2024-06-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0008_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
