# Generated by Django 5.0.6 on 2024-07-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0014_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.IntegerField(default=None),
        ),
    ]
