# Generated by Django 5.0.6 on 2024-08-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0016_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
