# Generated by Django 5.0.6 on 2024-08-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0017_gamerequest_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
