# Generated by Django 5.0.6 on 2024-09-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0020_chatroom_chatmessage_user_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='edited_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
