# Generated by Django 5.0.6 on 2024-09-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0021_alter_chatmessage_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='read_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
