# Generated by Django 5.0.6 on 2025-01-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0023_remove_chatmessage_read_at_chatroom_group_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='opponent',
            new_name='black',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='challenger',
            new_name='white',
        ),
        migrations.AddField(
            model_name='game',
            name='fen_notation',
            field=models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq -', max_length=90),
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(choices=[('w', 'white'), ('b', 'black')], max_length=1)),
                ('notation', models.CharField(max_length=7)),
                ('start_x', models.PositiveSmallIntegerField()),
                ('start_y', models.PositiveSmallIntegerField()),
                ('end_x', models.PositiveSmallIntegerField()),
                ('end_y', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='chess.game')),
            ],
        ),
        migrations.DeleteModel(
            name='UserChannel',
        ),
    ]
