# Generated by Django 5.0.6 on 2025-01-06 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0024_rename_opponent_game_black_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='white',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='white', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
